name: wtfisthiscrap
favicon: null
layout_spectrum: 0.6035678533371538
typography_spectrum: 0.3866748558357358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.879767463542521
  lightness: 0.19255937356501818
  saturation: 0.930427011102438
  rhythmicContrast: 0.5241562670562416
purpose: []
